### ISSUE TITLE
[BUG] [GUI]

### ISSUE THREAD

**Issue by jrviz** [bitfocus/companion#1572]
New GUI. Unicode characters not displayed in button text. Text shows &#xxxxxx; characters with no conversion.

Observed on Windows headless dev environment + second Windows PC using a distribution build.

**Comment by Julusian** [comment]
fixed

**Comment by jrviz** [comment]
Fixed for main button text but unicode character does not show on text of preset button when viewed in preset panel  or dropped into a bank. It will render correctly if button edited in place.

**Comment by scotttroyer** [comment]
Confirming that this is still happening on Companion PI 3.1.2 on a Raspberry PI 400.
