### ISSUE TITLE
X-keys Keypads are held by Companion Even when Disabled in Settings

### ISSUE THREAD

**Issue by JustAddSoftware** [bitfocus/companion#1687]
If an X-keys keypad is connected to the computer when Companion starts, Companion is grabbing that connection and not releasing it even if the X-keys keypad is disabled in the surface settings.  This prevents other software from using the keypad.  Sometimes quitting Companion and then starting my other software is sufficient.  Other times, I literally have to disconnect the keypad from the computer and reconnect it.  If Companion is started after other software that would access the keypad, Companion respects this and doesn't even show the keypad in the list of surfaces.

Please let me know if you need any more information.

Thank you.

Jon

**Comment by JeffreyDavidsz** [comment]
Pull request #1688 should fix this

**Comment by JustAddSoftware** [comment]
This is still not fixed.  If you have the keypad plugged in and start companion, it doesn't play nice.  It turns the blue LEDs on on all the keys.  And even after you quit Companion, the USB connection is not released.  The only way to allow another app to use the keypad is to unplug the USB connection and reconnect it.  And this happens even with the checkbox unchecked.  Companion should make no connection to the keypad.  Enumerating devices on the USB bus can be done w/o connecting.  Connection should only be allowed AFTER the enable checkbox is checked.

**Comment by JustAddSoftware** [comment]
Further info - If Companion is running and the keypad is connected, Companion does not automatically grab the keypad.  Other software can then use it.  But as soon as you scan USB devices, Companion grabs the device and renders it unable to be used by anything else.  As Companion starts with the computer, it will always grab the keypad.  It's not always convenient to unplug and re-plug the keypad  every time you start your computer.

**Comment by BasilChessman** [comment]
Was this ever sorted out?

**Comment by JeffreyDavidsz** [comment]
Yes, it's in the latest version
