### ISSUE TITLE
[BUG] [BETA] OSC button text updates in quick succession cause surface to disconnect

### ISSUE THREAD

**Issue by BryanCrotaz** [bitfocus/companion#1910]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sending button text updates over OSC, two pages in quick succession (from OBS python script). Stream Deck XL crashes and goes black, and Companion has to rescan USB to get it back. Updates were not applied.

### Steps To Reproduce

Send 64 button text changes over OSC (I'm using page 9 and page 8)

### Expected Behavior

Shouldn't crash the streamdeck connection

### Environment (please complete the following information)

```markdown
- OS: Window 10
- Browser: Chrome
- Companion Version: 2.2.0 (2.2.0+3880aafd507d)
```

**Comment by BryanCrotaz** [comment]
Only happens when the page being edited is visible on the Streamdeck

**Comment by Julusian** [comment]
Good spot.
fixed in 3897

**Comment by BryanCrotaz** [comment]
Still seeing it in [2.2.0 (2.2.0+3897-8d65a0c6)](https://bitfocus.io/companion/)

**Comment by BryanCrotaz** [comment]
Ah - found it. Here's the real bug:
https://github.com/bitfocus/companion/issues/1911
