### ISSUE TITLE
Lots of connection and BirdDog PTZ issues after latest windows updates? [BUG]

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2033]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After the latest Windows updates and on the latest Betas I am having various modules fail connection and also having weird issues with the BirdDog PTZ module.  The camera goes to random presets when called and loses connection randomly.  Other modules such as GlobalCache itach, Vicreo, etc also fail to estabilish a connection at all.  All is well when Windows update rolled back.  Anyone else noticing this?
Thanks

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
Windows 10 or 11?
What version of companion? I know there were some issues in 2.2.0 with birddog ptz having similar behaviour to what you describe, but I havent heard anything for the other modules

**Comment by obcocav** [comment]
@Julusian .  Sorry was frantically trying to fix the issues before service and didn't give many details...

Its Win10.  Companion 2.2.0 beta 4445 and tried 4443 also.  I think I was just able to rule out the Windows update itself.  That appears to have been a driver issue with one of the "Optional updates".  The one I had installed was actually newer than what Win Update replaced it with.  It was not one of the general security updates causing the issue.  More coincidence.

It does appear to be an issue with the latest builds though as I just tried 4445 arm64 on my Mac and had similar issues.  One of the symptoms I neglected to mention was a non responsive web GUI.  My stream decks seem to respond fine but the Companion web interface becomes unresponsive.  This just occurred even on the Mac build at home via VPN.

**Comment by Julusian** [comment]
There was an issue with the birddog-ptz in 2.2.1 and some beta builds, which is fixed in 2.2.2 and recent betas.
Hopefully updating to that will resolve this. If not then we can reopen and try to dig deeper

**Comment by obcocav** [comment]
@Julusian .  Just tried the latest beta 2.3.0.  For the record the problem is still present.  Unable to call or set any presets over 9.  But my understanding from the discussion with @jmcc94 is that this is a known API bug currently and will be fixed with the next firmware for the cameras.  Thanks!
