### ISSUE TITLE
[BUG] Beta 4.0 Trigger logic conditions missing

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion#3305]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I believe the change #3030 has stopped the conditions in the LOGIXC statements in 3.5 from being imported. The new trigger logic is empty after loading up the config file.

This is how the code looks in 3.5.2:

<img width="679" alt="Image" src="https://github.com/user-attachments/assets/20c72eac-5eb5-4f1b-869e-4cff50a99ca7" />

And this is the same trigger in 4.0 beta:

<img width="675" alt="Image" src="https://github.com/user-attachments/assets/20fca010-1f36-4c5d-a063-b0439a2ee642" />

### Steps To Reproduce

Import 3.5.2 config file with logic conditions on trigger

### Expected Behavior

The logic operation should import the conditions correctly.

### Environment (please complete the following information)

```markdown
- OS:Mac Sequoia 15.3.1
- Browser: Safari
- Companion Version: 4.0 beta
```

**Comment by ChrisSW58** [comment]
Anyone picking up on this as without it beta 4 testing and development has ground to a halt....?

**Comment by Julusian** [comment]
I've been distracted on more fun new things, so haven't looked through the bugs in a little bit.
I'll get to it soon

**Comment by ChrisSW58** [comment]
Thanks Julian - I do appreciate your work and time taken

**Comment by Julusian** [comment]
This should be fixed now.

**Comment by ChrisSW58** [comment]
Many thanks - much appreciated

**Comment by ChrisSW58** [comment]
Still not correct I’m afraid. The action is being loaded in but the values are missing - see attached.

<img width="629" alt="Image" src="https://github.com/user-attachments/assets/156a9ff3-0267-4881-ac23-e3b1b400855e" />

**Comment by ChrisSW58** [comment]
Hi there - just wondering where this is now as I can't see it in the Companion 4.0 plan.... Sorry for being a pain.

**Comment by ChrisSW58** [comment]
Actually working correctly...my mistake. Apologies. Sorted.

**Comment by ChrisSW58** [comment]
Actually working correctly...my mistake. Apologies. Sorted.
