### ISSUE TITLE
[BUG] 4.1 Import of just Custom Expressions reset everything

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion#3639]
### Make sure you're on the latest stable or beta build

- [x] I have tested this on the latest stable or beta release

### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion and not a specific module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When I import just custom expression variables, it is resetting my whole configurations.  All of the pages, connections, etc are being removed.

### Steps To Reproduce

1. Create a configuration that has multiple pages, custom variables, triggers, connections, custom expressions
2. Export the config with just expression variables
3. Import the just exported configuration and it should only allow expression variables to be imported.
4. Click the Import Selected Components.
5. You will now see that everything except for the connections that the expression uses are left.  The pages, connections, triggers, variables are all reset.

### Expected Behavior

I expected it to just import the custom expression variables and remove any that already existed.

### Environment (please complete the following information)

```markdown
- OS: MAC 15
- Browser: Chrome
- Companion Version: 4.1.0 stable
```

### Additional context

[My Expression Export](https://github.com/user-attachments/files/22371595/Justins-Air-4.ts.net.lan_2025-09-16-13.json)

**Comment by Julusian** [comment]
ok yeah, the partial import is a bit flawed...

the ui is sending 'true' for the import of things that are not available to be imported, resulting in the reset logic performing the reset of them.

And even if that werent the case, resetting the connections is hardcoded to true, and it always re-imports those so that will lose data too.

This might be non-trivial to do, so I am considering going with the easy solution of removing that button in 4.1, and redoing it in 4.2

**Comment by Julusian** [comment]
I think I have a fix for this that seems pretty safe. Fixed in betas, will be in 4.1.1

**Comment by digitaldrummerj** [comment]
@Julusian this is not fully fixed.  In 4.1.1, it is still resetting the custom variables when you import just the Expresson variables.

**Comment by Julusian** [comment]
ok, well I think this needs a lot more thought on how to handle, so I'm going to simply hide that bit of the ui instead for 4.1.2

the problem is that a lot of the import logic was written assuming it would be doing a full reset + import, so even now many bits of it are doing a `replaceX(` call, often to nothing.

**Comment by Julusian** [comment]
@digitaldrummerj could you give this another try with the betas, and see if you can spot any other cases that we have missed?
