### ISSUE TITLE
[BUG]Connection Collections Reordering/Drag and Drop Breaking

### ISSUE THREAD

**Issue by jreynolds67** [bitfocus/companion#3647]
### Make sure you're on the latest stable or beta build

- [x] I have tested this on the latest stable or beta release

### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion and not a specific module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

It appears that the new collections feature in 4.1.0 seems to break after a few uses on the connection page. Only collections that are at the top of the list are able to be reordered, any below it just do not grab and reorder. Grabbing connections individually seems to work generally well, it is when trying to move between collections, move collections and especially nest/unnest collections that it seems to break. Tested on Mac and Windows, Safari and Chrome.
Edit: Further investigation seems that moving a group when the group above it is expanded is a repeatable issue.

### Steps To Reproduce

Create a few collections. Move them around in the list. Eventually any collections that are not the top one will stop reordering.

### Environment (please complete the following information)

```markdown
- OS: Windows 11 and MacOS Tahoe
- Browser: Chrome and Safari
- Companion Version: 4.1.0
```

**Comment by Julusian** [comment]
This is fixed in 4.1.1

**Comment by michaelroper** [comment]
Just to note, I'm still seeing this same behaviour on v4.2.6 - though it only seems to exhibit when at least one collection is expanded, then any collections after the open one can't be dragged and reordered. If all collections are closed, all can be reordered.
