### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SamSMithy15** [bitfocus/companion#3682]
### Make sure you're on the latest stable or beta build

- [x] I have tested this on the latest stable or beta release

### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion and not a specific module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Our Stream Deck Mini (6-key) does not display any buttons or respond when connected through an Elgato Network Dock. The device powers on and shows the standby screen, and Companion recognizes it as connected but the Stream Deck stays stuck on the standby image and never updates. We can change  pages through the Web UI but the Stream Deck screen doesn’t change.

We have tried multpiple things and found out:

Other Stream Deck models work fine with the same Network Dock.
The Mini works normally with the official Elgato Stream Deck app through the same dock.
We’ve tried multiple USB-C adapters with identical results.

This behavior seems specific to Companion when used with the Stream Deck Mini via a network dock.

### Steps To Reproduce

1. Connect a Stream Deck Mini (6-key) to an Elgato Network Dock.
2. Launch Companion.
3. Observe that Companion detects the Stream Deck and shows it as connected.
4. Notice that the Stream Deck display remains on the standby image and never loads the Companion layout.

### Expected Behavior

The Stream Deck Mini should load and display the Companion button layout and respond to input, just like larger Stream Deck models do when connected through the same dock.

### Environment (please complete the following information)

```markdown
- OS: N/A
- Browser: Chrome
- Companion Version: 4.1.1
```

**Comment by sparks-alec** [comment]
I am experiencing this as well. Companion 4.1.1 with a Stream Deck Mini attached to a Network Dock. If I connect a Stream Deck Scissor to the same Network Dock, it works just fine.

**Comment by Julusian** [comment]
Can you check the model number of your streamdeck (should be written on the bottom), and the firmware version reported by the elgato software.

Im also curious if it works when connected directly to companion

**Comment by sparks-alec** [comment]
Mine is `20GAI9901` with firmware `3.03.002`. Works fine when connected directly to the Mac running Companion, and works with the Elgato Stream Deck App when connected via the Network Dock. So it only doesn't like the combo of Network Dock + Companion.

**Comment by Julusian** [comment]
This is fixed in 4.1.2

**Comment by avcabob** [comment]
This bug is back for me with Companion 4.2.6 and stream deck mini firmware 3.03.003
