### ISSUE TITLE
Button may be drawn on incorrect page after "Set surface to page" action

### ISSUE THREAD

**Issue by SteveTherrien** [bitfocus/companion#596]
**Describe the bug**
Setting a button's action to change to a different page and also change a button's style (background or text color) in the current page causes that button to be drawn on the wrong page.

**To Reproduce**
1. Set two actions for button 1.1:
   - `internal: Set surface to page` to page 2
   - `internal: Button Background Color` of 1.2 to red
2. Press button 1.1

Page will change to page 2, but button 1.2 will be drawn in place of button 2.2.

Reordering the button's actions works as expected.

**Expected behavior**
Button 2.2 will be drawn normally.

**Screenshots**
![button actions](https://user-images.githubusercontent.com/9618303/55695982-da497580-596f-11e9-9344-3969e08fb035.png)

![bug](https://user-images.githubusercontent.com/9618303/55696149-89864c80-5970-11e9-81ec-b08ad11608df.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser Chrome
 - Version 73

**Comment by josephdadams** [comment]
@SteveTherrien are you still having this problem? (Just trying to rule out stale bugs.) Thanks!

**Comment by Julusian** [comment]
@josephdadams I suspect this is a duplicate of https://github.com/bitfocus/companion/issues/729 but with a different STR

**Comment by josephdadams** [comment]
#596 (this one, #729, #595, and #769 all sound a lot alike...

**Comment by istnv** [comment]
> #596 (this one, #729, #595, and #769 all sound a lot alike...

They are. The **Internal: Set surface to page** should be fixed and I have a patch coming for the other internal page change actions.

**Comment by SteveTherrien** [comment]
@josephdadams, yes, this problem is still present in HEAD (2020-01-10).

I tried it with @istnv's [PR 953](https://github.com/bitfocus/companion/pull/953) but it didn't make a difference. I'm using the web emulator for my tests (no Stream Deck available at the moment).

Here's a [backup config](https://github.com/bitfocus/companion/files/4049868/issue-596.companionconfig.txt) you can restore to test this locally.

**Comment by istnv** [comment]
That one's different than the others I fixed. The page gets changed before the color change happens. 
If you notice the button number, it is a 'stale' picture issue similar to the others.
Quick fix: swap the order to change background before changing pages.
I shouldn't happen though. I'll try to look at it later today.
